stages:
  - test_stage
  # - lint
  # - build
  # - deploy-test
  # - deploy-prod

variables:
  imageName: $CI_REGISTRY_IMAGE
  tag: $CI_PIPELINE_IID

Test stage:
  stage: test_stage
  script: echo $imageName $tag

# Lint helm:
#   # TODO

# Build:
#   stage: build
#   image: docker:20.10.12
#   services:
#     - docker:20.10.12-dind
#   before_script:
#     - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
#     - # TODO
#   script:
#     - # TODO

# Deploy Test:
#   # TODO

# Stop Test:
#   # TODO

# Deploy Prod:
#   # TODO