{{ if and (eq .Values.pg.enabled true) (eq .Values.pg.persist.enabled false) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pg
spec:
  selector:
    app: {{ include "vaultwarden.fullname" . }}-pg
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pg
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" . }}-pg
  replicas: 1
  template:
    metadata:
        labels:
          app: {{ include "vaultwarden.fullname" . }}-pg
        annotations:
          checksum/config: {{ include (print $.Template.BasePath "/common/database_url_secret.yaml") $ | sha256sum }}
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" . }}-pg
        {{ with .Values.pg }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: {{ include "vaultwarden.fullname" $ }}-pg
        {{ end }}
{{ end }}