{{ if and (eq .Values.pg.enabled true) (eq .Values.pg.persist.enabled false) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pg
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" . }}-pg
  replicas: 1
  template:
    metadata:
        labels:
          app: {{ include "vaultwarden.fullname" . }}-pg
        annotations:
          checksum/config: {{ include (print $.Template.BasePath "/shared/database_url_secret.yaml") $ | sha256sum }}
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" . }}-pg
        {{ with .Values.pg }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .password }}
        - name: POSTGRES_USER
          value: {{ .username }}
        - name: POSTGRES_USER
          value: {{ .db }}
        {{ end }}
{{ end }}