{{ with .Values.pg }}
{{ if and (eq .enabled true) (eq .persist.enabled true) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-pg
  labels:
    persist: postgres
spec:
  clusterIP: None
  selector:
    app: {{ include "vaultwarden.fullname" $ }}-pg
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-pg
  labels:
    persist: postgres
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" $ }}-pg
  serviceName: {{ include "vaultwarden.fullname" $ }}-pg
  replicas: {{ .persist.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "vaultwarden.fullname" $ }}-pg
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" $ }}-pg
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: storage
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: username
    volumeClaimTemplates:
    - metadata:
      name: storage
    spec:
      accessMode: [ "ReadWriteOnce" ]
      StorageClass: {{ .persist.StorageClass }}
      resources:
        requests:
          storage: {{ .persist.size }}
{{ end }}
{{ end }}