{{ with .Values.pg.persist }}
{{ if .enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-pg
spec:
  storageClassName: custom
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage
{{ end }}
{{ end }}