{{ with .Values.pg }}
{{ if eq .enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-pg
data:
  POSTGRES_USER: {{ .username | b64enc }}
  POSTGRES_PASSWORD: {{ .password | b64enc }}
  POSTGRES_DB: {{ .db | b64enc }}
{{ end }}
{{ end }}