{{ with .Values.pg }}
{{ if eq .enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-creds
data:
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}
  db: {{ .db | b64enc }}
{{ end }}
{{ end }}