{{ if and (eq .Values.pg.enabled true) (eq .Values.pg.persist.enabled false) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pg
spec:
  selector:
    app: {{ include "vaultwarden.fullname" . }}-pg
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
{{ end }}