{{ with .Values.vaultwarden.ingress }}
{{ if eq .enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "vaultwarden.fullname" $ }}
  annotations:
    kubernetes.io/tls-acme: {{ .tls.enabled | quote }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: {{ .className }}
  {{ if eq .tls.enabled true }}
  tls:
  - hosts:
    - {{ .domain }}
    secretName: {{ .tls.secretName }}
  {{ end }}
  rules:
  - host: {{ .domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "vaultwarden.fullname" $ }}
            port:
              number: 80
{{ end }}
{{ end }}