apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "vaultwarden.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/common/database_url_secret.yaml") $ | sha256sum }}
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" . }}
        {{ with .Values.vaultwarden }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
          - containerPort: 80
        env:
        {{ if eq $.Values.pg.persist.enabled false }}
        - name: I_REALLY_WANT_VOLATILE_STORAGE
          value: "true"
        {{ end }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "vaultwarden.fullname" $ }}-db
              key: url
        {{ end }}
      imagePullSecrets:
        - name: {{ $.Values.vaultwarden.imagePullSecrets }}
