{{ with .Values.vaultwarden.admin }}
{{ if eq .enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-admin
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" $ }}-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "vaultwarden.fullname" $ }}-admin
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/common/database_url_secret.yaml") $ | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/admin/admin_token_secret.yaml") $ | sha256sum }}
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" $ }}-admin
        {{ with $.Values.vaultwarden }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
          - containerPort: 80
        {{ end }}
        env:
        {{ if eq $.Values.pg.persist.enabled false }}
        - name: I_REALLY_WANT_VOLATILE_STORAGE
          value: "true"
        {{ end }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "vaultwarden.fullname" $ }}-db
              key: url
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "vaultwarden.fullname" $ }}-admin
              key: adminToken
      imagePullSecrets:
        - name: {{ $.Values.vaultwarden.imagePullSecrets }}
{{ end }}
{{ end }}