{{ with .Values.vaultwarden.admin }}
{{ if eq .enabled true }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-admin
data:
  adminToken: {{ .token | b64enc}}
{{ end }}
{{ end }}