{{ with .Values.vaultwarden.admin.basicAuth }}
{{ if eq .enabled true }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
data:
  auth: {{ htpasswd .username .password | b64enc | quote }}
{{ end }}
{{ end }}