{{ with .Values.vaultwarden.ingress }}
{{ if eq .enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "vaultwarden.fullname" $ }}-admin
  annotations:
    kubernetes.io/tls-acme: {{ .tls.enabled | quote }}
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    {{ if eq $.Values.vaultwarden.admin.basicAuth.enabled true }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    {{ end }}
spec:
  ingressClassName: {{ .className }}
  {{ if eq .tls.enabled true }}
  tls:
  - hosts:
    - {{ .domain }}
    secretName: {{ .tls.secretName }}
  {{ end }}
  rules:
  - host: {{ .domain }}
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ include "vaultwarden.fullname" $ }}-admin
            port:
              number: 80
{{ end }}
{{ end }}