{{ if eq .Values.vaultwarden.admin.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-admin
spec:
  selector:
    app: {{ include "vaultwarden.fullname" $ }}-admin
  ports:
  - port: 80
    targetPort: 80
{{ end }}