# instance - dolinskiydmitri-552
nameOverride: vaultwarden
fullnameOverride: vaultwarden

vaultwarden:
  imagePullSecrets: registry-credentials
  image:
    repository: vaultwarden/server
    tag: 1.25.2-alpine
    pullPolicy: IfNotPresent
  web:
    podAnnotations: {}
  ingress:
    enabled: true
    className: nginx
    domain: ""
    tls:
      enabled: true
      secretName: vaultwarden-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
  admin:
    enabled: true
    podAnnotations: {}
    token: some_secure_token
    basicAuth:
      enabled: true
      username: admin
      password: adminadmin
  pg:
    url: ""
pg:
  enabled: true
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  env:
        - name: POSTGRES_PASSWORD
          value: vaultwarden_password
        - name: POSTGRES_USER
          value: vaultwarden_user
        - name: POSTGRES_DB
          value: vaultwarden
  podAnnotations: {}

  username: postgres
  password: some_password
  db: postgres