# instance - dolinskiydmitri-577
nameOverride: vaultwarden
fullnameOverride: vaultwarden

vaultwarden:
  imagePullSecrets: registry-credentials
  image:
    repository: vaultwarden/server
    tag: 1.25.2-alpine
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: nginx
    domain: ""
    tls:
      enabled: true
      secretName: vaultwarden-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
  admin:
    enabled: true
    podAnnotations: {}
    token: some_secure_token
    basicAuth:
      enabled: true
      username: admin
      password: adminadmin

pg:
  enabled: true
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  podAnnotations: {}

  username: postgres
  password: some_password
  db: postgres

  persist:
    enabled: true
    replicas: 1
    storageClass: custom
    size: 1Gi