{{ with .Values.vaultwarden.admin }}
{{ if eq .enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-admin
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" $ }}-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "vaultwarden.fullname" $ }}-admin
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" $ }}-admin
      {{ with $.Values.vaultwarden }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
          - containerPort: 80
      {{ end }}
        env:
        - name: I_REALLY_WANT_VOLATILE_STORAGE
          value: 'true' 
        {{ if eq $.Values.pg.enabled true }}
        {{ with $.Values.pg }}
        - name: DATABASE_URL
          value: postgresql://{{ .username }}:{{ .password }}@{{ include "vaultwarden.fullname" $ }}-pg:5432/{{ .db }}
        {{ end }}
        {{ else if eq $.Values.pg.enabled false }}
          value: {{ required "Database URL was not provided" .pg.url}}
        {{ end }}
        - name: ADMIN_TOKEN
          value: {{ .token }}
      imagePullSecrets:
        - name: {{ $.Values.vaultwarden.imagePullSecrets }}
{{ end }}
{{ end }}
---
{{ if eq .Values.vaultwarden.admin.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-admin
spec:
  selector:
    app: {{ include "vaultwarden.fullname" $ }}-admin
  ports:
  - port: 80
    targetPort: 80
{{ end }}
---
{{ with .Values.vaultwarden.ingress }}
{{ if eq .enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "vaultwarden.fullname" $ }}-admin
  annotations:
    kubernetes.io/tls-acme: {{ .tls.enabled | quote }}
    {{ if eq $.Values.vaultwarden.admin.basicAuth.enabled true }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    {{end }}
spec:
  ingressClassName: {{ .className }}
  {{ if eq .tls.enabled true }}
  tls:
  - hosts:
    - {{ .domain }}
    secretName: {{ .tls.secretName }}
  {{ end }}
  rules:
  - host: {{ .domain }}
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ include "vaultwarden.fullname" $ }}-admin
            port:
              number: 80
{{ end }}
{{ end }}