{{ if eq .Values.pg.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pg
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" . }}-pg
  replicas: 1
  template:
    metadata:
        labels:
          app: {{ include "vaultwarden.fullname" . }}-pg
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" . }}-pg
        {{ with .Values.pg }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .password }}
        - name: POSTGRES_USER
          value: {{ .username }}
        - name: POSTGRES_USER
          value: {{ .db }}
        {{ end }}
{{ end }}
---
{{ if eq .Values.pg.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pg
spec:
  selector:
    app: {{ include "vaultwarden.fullname" . }}-pg
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
{{ end }}