{{ with .Values.vaultwarden.admin.basicAuth }}
{{ if eq .enabled true }}
apiVersion: v1
data:
  auth: {{ htpasswd .username .password | b64enc | quote }}
kind: Secret
metadata:
  name: basic-auth
type: Opaque
{{ end }}
{{ end }}