apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "vaultwarden.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "vaultwarden.fullname" . }}
    spec:
      containers:
      - name: {{ include "vaultwarden.fullname" . }}
      {{ with .Values.vaultwarden }}
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
          - containerPort: 80
        env:
        - name: I_REALLY_WANT_VOLATILE_STORAGE
          value: 'true' 
        {{ if eq $.Values.pg.enabled true }}
        {{ with $.Values.pg }}
        - name: DATABASE_URL
          value: postgresql://{{ .username }}:{{ .password }}@{{ include "vaultwarden.fullname" $ }}-pg:5432/{{ .db }}
        {{ end }}
        {{ else if eq $.Values.pg.enabled false }}
          value: {{ required "Database URL was not provided" .pg.url}}
        {{ end }}
      {{ end }}
      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
spec:
  selector:
    app: {{ include "vaultwarden.fullname" . }}
  ports:
  - port: 80
    targetPort: 80
---
{{ with .Values.vaultwarden.ingress }}
{{ if eq .enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "vaultwarden.fullname" $ }}
  annotations:
    kubernetes.io/tls-acme: {{ .tls.enabled | quote }}
spec:
  ingressClassName: {{ .className }}
  {{ if eq .tls.enabled true }}
  tls:
  - hosts:
    - {{ .domain }}
    secretName: {{ .tls.secretName }}
  {{ end }}
  rules:
  - host: {{ .domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "vaultwarden.fullname" $ }}
            port:
              number: 80
{{ end }}
{{ end }}