{{ with .Values.pg }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" $ }}-db
stringData:
  url: postgresql://{{ .username }}:{{ .password }}@{{ include "vaultwarden.fullname" $ }}-pg:5432/{{ .db }}
{{ end }}